name: CI

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: python3 -m pip install -r tools/requirements.txt --no-warn-script-location
      - name: Build
        run: |
            mkdir built
            python3 tools/build.py filters/main.yml --hosts built/hosts.txt --abp built/abp.txt --domains built/domains.txt
            brotli built/*
      - name: Ensure files have contents
        run: |
            [ $(wc -l < built/hosts.txt) -gt 100 ]
            [ $(wc -l < built/abp.txt) -gt 100 ]
            [ $(wc -l < built/domains.txt) -gt 100 ]
      - name: Make the working tree safe
        run: git config --global --add safe.directory /__w/not-on-my-shift/not-on-my-shift
      - name: Publish
        uses: stefanzweifel/git-auto-commit-action@4d160c5e4d67c62e67f03ae49aa38359e964139a
