name: CI

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
            chmod +x build.bash
            bash build.bash
      - name: Ensure files have contents
        run: |
            [ $(wc -l < built/hosts.txt) -gt 100 ]
            [ $(wc -l < built/abp.txt) -gt 100 ]
            [ $(wc -l < built/domains.txt) -gt 100 ]
      - name: Make the working tree safe
        run: git config --global --add safe.directory /__w/not-on-my-shift/not-on-my-shift
      - name: Publish
        uses: stefanzweifel/git-auto-commit-action@4d160c5e4d67c62e67f03ae49aa38359e964139a
        with:
          commit_message: "Updated filters"
